/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgenteRouteImport } from './routes/agente'
import { Route as ContabilRouteImport } from './routes/contabil'
import { Route as IntegracaoFzapRouteImport } from './routes/integracao-fzap'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as ApiPublicFzapRouteImport } from './routes/api/public/fzap'
import { Route as ApiPublicWhatsappRouteImport } from './routes/api/public/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenteRoute = AgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilRoute = ContabilRouteImport.update({
  id: '/contabil',
  path: '/contabil',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracaoFzapRoute = IntegracaoFzapRouteImport.update({
  id: '/integracao-fzap',
  path: '/integracao-fzap',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFzapRoute = ApiPublicFzapRouteImport.update({
  id: '/api/public/fzap',
  path: '/api/public/fzap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappRoute = ApiPublicWhatsappRouteImport.update({
  id: '/api/public/whatsapp',
  path: '/api/public/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/contabil': typeof ContabilRoute
  '/integracao-fzap': typeof IntegracaoFzapRoute
  '/manual': typeof ManualRoute
  '/api/public/fzap': typeof ApiPublicFzapRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/contabil': typeof ContabilRoute
  '/integracao-fzap': typeof IntegracaoFzapRoute
  '/manual': typeof ManualRoute
  '/api/public/fzap': typeof ApiPublicFzapRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/contabil': typeof ContabilRoute
  '/integracao-fzap': typeof IntegracaoFzapRoute
  '/manual': typeof ManualRoute
  '/api/public/fzap': typeof ApiPublicFzapRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agente'
    | '/contabil'
    | '/integracao-fzap'
    | '/manual'
    | '/api/public/fzap'
    | '/api/public/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agente'
    | '/contabil'
    | '/integracao-fzap'
    | '/manual'
    | '/api/public/fzap'
    | '/api/public/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/agente'
    | '/contabil'
    | '/integracao-fzap'
    | '/manual'
    | '/api/public/fzap'
    | '/api/public/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenteRoute: typeof AgenteRoute
  ContabilRoute: typeof ContabilRoute
  IntegracaoFzapRoute: typeof IntegracaoFzapRoute
  ManualRoute: typeof ManualRoute
  ApiPublicFzapRoute: typeof ApiPublicFzapRoute
  ApiPublicWhatsappRoute: typeof ApiPublicWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agente': {
      id: '/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabil': {
      id: '/contabil'
      path: '/contabil'
      fullPath: '/contabil'
      preLoaderRoute: typeof ContabilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracao-fzap': {
      id: '/integracao-fzap'
      path: '/integracao-fzap'
      fullPath: '/integracao-fzap'
      preLoaderRoute: typeof IntegracaoFzapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fzap': {
      id: '/api/public/fzap'
      path: '/api/public/fzap'
      fullPath: '/api/public/fzap'
      preLoaderRoute: typeof ApiPublicFzapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp': {
      id: '/api/public/whatsapp'
      path: '/api/public/whatsapp'
      fullPath: '/api/public/whatsapp'
      preLoaderRoute: typeof ApiPublicWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenteRoute: AgenteRoute,
  ContabilRoute: ContabilRoute,
  IntegracaoFzapRoute: IntegracaoFzapRoute,
  ManualRoute: ManualRoute,
  ApiPublicFzapRoute: ApiPublicFzapRoute,
  ApiPublicWhatsappRoute: ApiPublicWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
